# Extra autostart processes
exec-once = wl-clip-persist --clipboard both
exec-once = ~/.config/hypr/scripts/monitor-watch.sh                 # restart waybar on monitor hotplug

# Start on workspace 1
exec-once = hyprctl dispatch workspace 1

# Scratchpad terminal
exec-once = hyprctl dispatch exec [workspace special:scratchpad silent] ghostty

# Startup layout
exec-once = ~/.config/hypr/scripts/label-webapps.sh
exec-once = uwsm-app -- chromium about:blank --disable-session-restore  # workspace 1
exec-once = hyprctl dispatch exec [workspace 2 silent] ghostty                              # workspace 2
exec-once = uwsm-app -- obsidian -disable-gpu --enable-wayland-ime                         # workspace 3
exec-once = uwsm-app -- Telegram                                                            # workspace 4
